### PR TITLE
Yes

### PR DESCRIPTION
**Pull request by Deftu**

### CODE REVIEW

**Comment by Mqisty** [comment]
no

**Comment by MicrocontrollersDev** [comment]
moisture said no sorry will be closing this

**Comment by Deftu** [comment]
> no

:(

**Comment by MicrocontrollersDev** [comment]
since it seems to based on shotify (I haven't used the mod so idk any differences or whatever), should shotify be updated and continue to get updates your mod will be replaced by it here. otherwise its fine

**Pull request merged**
