### PR TITLE
Grammar/spelling fixes, ease of access additions, some mod changes 

### PR DESCRIPTION
**Pull request by Mqisty**
Also was going to link mods mentioned in other mod's description but wanted to know what you thought first.

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
preferably description linked mods would direct to the place in the list where the mod is explained (if that makes sense) but don’t think i can do that in md. honestly i don’t think it matter much but i’d prefer if people actually went and checked what the mods were and saw incompatibilities or whatever i think as it is is best rn

**Comment by MicrocontrollersDev** [comment]
nah ur not gonna find anything not worth it

**Comment by Mqisty** [comment]
moulberrys server is no help either smh

**Comment by Mqisty** [comment]
btw what is the [TODO](https://github.com/MicrocontrollersDev/MigratingToLatest#internal-shader) here for

**Comment by MicrocontrollersDev** [comment]
todo was me being lazy and forgetting about it for months i’ll do that later

**Comment by Mqisty** [comment]
i think im done, lmk if i did anything wrong

**Comment by MicrocontrollersDev** [comment]
yeah ur right abt the link i just somehow missed that when i was switching them all to github (used to use modrinth links in the past)

**Review by MicrocontrollersDev — APPROVED** [review]
and i thought i was good at english
edit: okay no i know i’m not good at english but at least decent i guess

**Comment by Mqisty** [comment]
we all make mistakes 🤷‍♂️

**Pull request merged**
