### PR TITLE
add wyvtils and mojangster, fixes

### PR DESCRIPTION
**Pull request by Wyvest**
TODO:
Add mojangster

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
too lazy to check myself, does essential actually change the borderless fullscreen in 1.17? minecraft technically already has borderless but it just minimizes the game when tabbed out. last i checked, essential doesnt change this behavior

**Comment by Wyvest** [comment]
> too lazy to check myself, does essential actually change the borderless fullscreen in 1.17? minecraft technically already has borderless but it just minimizes the game when tabbed out. last i checked, essential doesnt change this behavior

It does.

**Comment by Wyvest** [comment]
NOT. I AM STUPID.

**Comment by Wyvest** [comment]
Ready to merge

**Comment by MicrocontrollersDev** [comment]
thank, will review/merge soon™️

**Comment by Wyvest** [comment]
you can merge now :+1:

**Pull request merged**
