### PR TITLE
added rainbowify

### PR DESCRIPTION
**Pull request by BobIsMyManager**

### CODE REVIEW

**Comment by MicrocontrollersDev** [comment]
looks good. might edit description a bit after i check rainbowify’s compatibility with blur mod

**Comment by BobIsMyManager** [comment]
Rainbowify has its own blur aswell so you dont really need both tho

**Comment by BobIsMyManager** [comment]
Idk if you can disable rainbow and have blur aswell

**Comment by MicrocontrollersDev** [comment]
im a pretty big fan of the customizability of the regular blur mod, including stuff like fade time. i guess you're right in that there isn't a reason in checking compatibility, just use one or the other

**Comment by BobIsMyManager** [comment]
On rainbowify you can only choose the blur amount, and it would probably look wierd if the blur fades at a different speed to the rainbow so unless there are other significant features, i dont see a reason to use them together

**Pull request merged**
