### PR TITLE
new column for optifine compatibility

### PR DESCRIPTION
**Pull request by MicrocontrollersDev**
any feedback would be appreciated

### CODE REVIEW

**Comment by BobIsMyManager** [comment]
Why would you still want to use optifine though, if you even bothered looking at this list the chances are that you were looking for better solutions anyway.

**Comment by MicrocontrollersDev** [comment]
my bad, worded poorly, was talking specifically about the optifine (mcpatcher) format for the resource pack stuff, and i also added if the mod is more customizable compared to optifine. i’ll reword this when i get the chance

**Comment by BobIsMyManager** [comment]
Ah ok, im not sure if "supports optifine format" is a good name for the collum as it doesnt make sense with some mods and also indicates that the collum should just be yes/no answers when that isnt the case

**Comment by MicrocontrollersDev** [comment]
closing for now. may come back to this in the future.

**Comment by BobIsMyManager** [comment]
For optifine format resource packs people can just use this https://github.com/supsm/MCPPPP

**Pull request closed without merging**
